# -*- coding: utf-8 -*-
# Auto-generated seed file - contains all 555 YTU courses
import sqlite3
from database import DB_PATH, init_db

ALL_COURSES = [
    ('BIO', 'BYM1201', 'Introduction to Bioengineering Dr. Cem Özel BYM4211 Tissue Engineering Mehmet Murat Özmen, Emrah Şefik Abamor', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'KIM1170', 'General Chemistry MES-4 BYM4101 Data Analysis and Visualization () Dr. Öğr. Üyesi Hatice Büşra Lüleci', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Perşembe'), 
    ('BIO', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM2071', 'Mass and Energy Balances Doç Dr. F. Tuğçe Şenberber Dumanl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM2101', 'Basic Principles in Molecular Biology Prof. Dr. Musa Türker BYM3501 Entrepreneurship and Project Management Dr. Selcen Ar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM2131', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM2321', 'Biochemistry in Bioengineering Doç. Dr. Murat Topuzoğullar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('BIO', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'BYM3031', 'Biomaterials Prof. Dr. Mehmet Murat Özmen BYM4381 Immunology Doç. Dr. Emrah Şefik Abamor', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM3321', 'Cell Culture Systems () Doç. Dr. Emrah Şefik Abamor BYM3601 Biosensors Dr. Mustafa Niğde ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'BYM3401', 'Separation Processes in Bioengineering Doç. Dr. Murat Topuzoğullar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Perşembe'), 
    ('BIO', 'BYM3511', 'Genetics Engineering Laboratory Prof. Dr. Dilek Bal', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM3521', 'Bioinstrumental Techniques Doç. Dr. Esma Özerol () BYM3531 Biomedical Electronics Prof. Dr. Ayhan Bingölbali () BYM3311 Introduction to Bioinformatics Dr. Öğr. Üyesi Hatice Büşra Lüleci (-A) BYM3361 Genetic Concepts Doç. Dr. Azade Attar ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM3921', 'Heat and Mass Transfer in Bioeng Doç. Dr. Benan İnan MES-4 BYM4801 Artificial Organs Doç. Dr. Azade Attar -A', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM4721', 'Nanotechnology in Bioengineering Dr. Pelin Pelit Aray', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM4741', 'Bioprocess engineering Doç. Dr. Benan İnan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BLM', 'BLM1011', 'Bilgisayar Bilimlerine Giriş', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM1991', 'İş Sağlığı ve Güvenliği 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2011', 'İstatistik ve Olasılık Hesapları', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2012', 'Nesneye Yönelik Programlama', 2, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2521', 'Ayrık Matematik', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2611', 'Lojik Devreler', 2, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2642', 'Bilgisayar Mühendisleri için Diferansiyel Denklemler', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'USS-2G', 'Üniversite Sosyal Seçmeli -1', 2, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('BLM', 'BLM3010', 'Bilgisayar Projesi', 3, 0, 3, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3011', 'İşletim Sistemleri', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3021', 'Algoritma Analizi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3041', 'Veritabanı Yönetimi', 3, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3042', 'Seminer ve Meslek Etiği', 3, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3061', 'Mikroişlemci Sistemleri ve Assembly Dili', 3, 0, 4, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3730', 'Blokzincir Temelleri', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MES1-3B', 'Mesleki Seçmeli 1-1', 3, 1, 3, 8, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'SOS1-3B', 'Sosyal Seçmeli 1-1', 3, 1, 3, 4, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('BLM', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'BLM3120', 'Bil.Er.Ar.Mot.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4011', 'Bilişim Sis. Güvenliği', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4021', 'Gömülü Sistemler', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4140', 'Kablosuz Mobil Ağlar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4800', 'Veri Madenciliğine Giriş', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM9000', 'Bitirme Çalışması', 4, 0, 4, 8, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BME4991', 'BME4991 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MES1-4B1', 'Mesleki Seçmeli 1-4', 4, 1, 3, 8, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'MES1-4B2', 'Mesleki Seçmeli 1-5', 4, 1, 3, 8, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'MES1-4G1', 'Mesleki Seçmeli 1-2', 4, 1, 3, 8, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'MES1-4G2', 'Mesleki Seçmeli 1-3', 4, 1, 3, 8, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'MES2-4G', 'Mesleki Seçmeli 2-1', 4, 1, 1, 3, 'Bölüm Seçmeli Havuzu', 0, None), 
    ('BLM', 'UMS-4G', 'Üniversite Mesleki Seçmeli', 4, 1, 3, 5, 'Üniversite Seçmeli Havuzu', 0, None), 
    ('BLM', 'USS-4B', 'Üniversite Sosyal Seçmeli -3', 4, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('BLM', 'USS-4G', 'Üniversite Sosyal Seçmeli -2', 4, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('BMD', 'BME1101', 'Introduction to Biomedical Engineering', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME1901', 'Introductory Computer Sciences', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'KIM1170', 'General Chemistry ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2011', 'Occupational Health And', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2303', 'Circuit Theory', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2901', 'Biochemistry Lab.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2911', 'Introduction to Human Anatomy & Physiology Classroom: BB06(Amfi)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BMD', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3161', 'Biosignal Processing', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3315', 'Analog Electronic Lab.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3323', 'Introduction to', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3325', 'Logic Design Lab.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3330', 'Biolectromagnetism', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3600', 'Biyomedikal Mühendisliğinde', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3711', 'Biothermodynamics', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3921', 'Biomechanics 1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM1011', 'EHM Giriş Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM1041', 'İş Sağl', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM1051', 'Algoritma Tasar', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Çarşamba'), 
    ('EHM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM2121', 'Devre ve Sistem Analizi Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2131', 'Elektromagnetik Alan Teorisi Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM2141', 'Lojik Devreler Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'EHM2161', 'Say', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM2171', 'Elektrik Devre Temelleri Laboratuvar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2191', 'Mühendislik Matematiği 2 Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'MDB2051', 'İngilizce Okuma ve Konuşma Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3111', 'Elektronik Devreler 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'EHM3121', 'Mikrodalga 1 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM3122', 'Haberleşme 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3131', 'Haberleşme 1 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3141', 'Mikroişlemci Sistemleri Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM3151', 'Elektronik Devreler 1 Laboratuvar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3181', 'Say', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM3731', 'Haberleşme Ağlar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM3741', 'Gömülü Sistemlerde Makine Öğrenmesi (TR) Murat Taşk', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4150', 'Gömülü Sistemlerde Donan', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4200', 'Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4260', 'Veri Haberleşmesi (ING) Tansal Güçlüoğlu B023 09.00 Pazartesi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4270', 'Hücresel Haberleşme Sistemleri 1 (ING) Shahen Shah B153 13.00', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4300', 'Fiber Optiğe Giriş (TR) Fikret Tokan B025 09.00 Sal', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4330', 'Optik Haberleşme Sistemleri (TR) Özlem Ünverdi B152 13.00', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4370', 'Mikroişlemcili Sistem Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4460', 'Uydu Haberleşmesinin Temelleri (ING) Ufuk Sakarya B153 09.00 Perşembe', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4830', 'Programlanabilir Lojik Devre Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4840', 'Görüntü İşleme Gr', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4880', 'Elektronik Savunma Sistemlerine Giriş (TR) Ahmet Serdar Türk B023 13.30', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4991', 'Çok Disiplinli Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM1071', 'ELM1071 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('ELK', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2040', 'ELM2040 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2061', 'ELM2061 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM2081', 'ELM2081 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2111', 'ELM2111 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2130', 'ELM2130 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2142', 'ELM2142 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi, Salı'), 
    ('ELK', 'ELM2090', 'ELM2090 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2110', 'ELM2110 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2121', 'ELM2121 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('ELK', 'ELM2010', 'ELM2010 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2140', 'ELM2140 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('END', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END1151', 'Computer Programming 1 Gr2 Doç. Dr. Mert EDALI', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1911', 'Occupational Health and Safety 1 Gr1 Arş. Gör. Dr. Meryem Ezgi ASLAN', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1991', 'Introduction to Industrial Engineering Gr1 ODITORYUM Prof. Dr. Umut Rıfat TUZKAYA', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2995', 'Manufacturing Processes Gr1 A310 Doç. Dr. Tolga MERT', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3455', 'Pazarlama Gr1 A415 Öğr. Gör. Dr. Ufuk BÖLÜKBAŞ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3975', 'Artificial Intelligence Gr2 A313 Doç. Dr. Ali KARAŞAN', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4665', 'Financial Management Gr1 A205 Dr. Öğr. Üyesi Evrim HACIOĞLU KAZAK', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4985', 'İş Hukuku Gr1 A107 Dr. Öğr. Üyesi Ahmet Reşat SARAOĞLU', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MTH3200', 'Savunma Sanayide Mühendislik Malzemeleri ve Stratejik Tedarik Zinciri Yönetimi Gr1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2151', 'Computer Programming 2 Gr1 Arş. Gör. Dr. Meryem Ezgi ASLAN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2961', 'Economics Gr1 B202 Prof. Dr. Feride GÖNEL', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2991', 'Probability Gr1 A310 Prof. Dr. Selin SONER KARA', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3875', 'Heuristic Optimization Methods Gr1 A308 Öğr. Gör. Dr. K. Büşra YILMAZER KAYA', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3965', 'Applied Artificial Learning Gr1 A319 Dr. Öğr. Üyesi Serkan SALTÜRK', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3995', 'Quality Engineering Gr2 A318 Arş. Gör. Dr. Aslıhan YILDIZ GÖKSOY', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH4800', 'Innovation Campus Artificial Intelligence (Samsung) Gr1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('GDA', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('GDA', 'GDM1301', 'GDM1301 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM1303', 'GDM1303 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('GDA', 'GDM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM1170', 'Genel Kimya () GDM 2301 G', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('GDA', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('GDA', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2091', 'Kütle ve Enerji Denklikleri Dr. Öğr. Üyesi Fatih BOZKURT GDM4595 İnsan Merkezli Yapay Zeka Dr. Öğr. Üyesi Duygu ÖZMEN', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM2112', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2172', 'GDM2172 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2181', 'Genel Mikrobiyoloji Doç. Dr. Banu METİN GDM3306 Fermentasyon Teknolojisi Prof. Dr. Muhammet ARICI GDM4111 G', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM2301', 'Analitik Kimya (', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM3211', 'Enstrümental Analizler (Lab) Doç. Dr. Nur ÇEBİ', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('GDA', 'GDM3231', 'GDM3231 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM3261', 'Reaksiyon Kinetiği Prof. Dr. Ömer Said TOKER', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM3271', 'Girişimcilik ve Proje Yönetimi Dr. Öğr. Üyesi Öznur SAROĞLU', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM3301', 'GDM3301 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'GDM3303', 'GDM3303 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM4121', 'GDM4121 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'GDM4301', 'GDM4301 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM4303', 'Su Ürünleri İşleme Teknolojisi Doç. Dr. Şenol KÖSE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4305', 'Süt ve Ürünleri Teknolojisi Prof. Dr. Osman SAĞDIÇ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4307', 'Et ve Ürünleri Teknolojisi (EN) Doç. Dr. Ruşen METİN YILDIRIM', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM4309', 'GDM4309 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('KIM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KIM1501', 'Genel Kimya 1 (KMB 210) (KMB 218)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM1041', 'Kimya Müh.Giriş İ. Doymaz (KMB 210)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'ITB1000', 'Sosyal Seçmeli Dersi', 2, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('KIM', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB2631', 'Mühendisler için Olasılık ve', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2601', 'İş Sağlığı ve Güv. 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2611', 'Kimya Müh. Hesap.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2621', 'Müh. için Fiz. Kimya S. Deniz (KMB 316) Y. Kalpaklı (KME 306)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3561', 'UMS Teknik İletişim (N. Tuğrul)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB3631', 'Artificial Intelligence for', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2631', 'Probability and Statistics for', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KIM1501', 'General Chem. 1 (KMB 316) (KMB 314)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM1041', 'Int. to Chem. Eng. D.Dinçer (KMB 210) İ.Küçük (KME 306)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'ITB1000', 'Social Elective Course', 2, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('KIM_ENG', 'KMB3631', 'Artificial Intelligence for Chemical Engineers (M. A. İnsel) (KMB 306)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM2601', 'Occ. Health & Safety-1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM2611', 'Chem. Eng.Calc.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM2621', 'Phy. Chem. For Eng. T. Gösterişli (KMB 322) F. Dumanli (KMB 314)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM2631', 'Probability and Statistics for Engineers', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3561', 'UMS Technical Communication (E. Akyol)', 2, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3501', 'Ent. & Project Man.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3511', 'Numerical Analysis', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3521', 'Heat Transfer in Chem. Eng.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3531', 'Chemical Eng. Thermo. 2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3541', 'Mass Transfer', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3551', 'Env. Technology J. Gülen', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM3591', 'Analysis Methods in Chemical Industry E. Derun', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4671', 'Chemical Engineering Economics T. U. Gösterişli', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4000', 'Graduation Thesis', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4611', 'Pro. Des. in Chemical Eng. I', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4621', 'Chemical Reactor Design', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4631', 'Process Dynamics and Control E. Yılmaz (KMB 314) E. Kıpçak (KMB 218)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4641', 'W. Recyc. J. Gülen KMM4691 Bioseperation (M. Yılmaz)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4651', 'Bio. E. Fund. (B. Özbek)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4721', 'Opt. in Chem. Eng. H. Sadıkoğlu', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM_ENG', 'KMM4751', 'Calc. in Multi-Component Sep. Systems', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1051', '.05 Öğr.Gör.Dr. SEYHAN ÖZEN A410 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1061', '.01 Öğr.Gör. Umut KINIT A313 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1062', '.01 Özlem EMANET A209 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2061', '.01 BEDRİ ONUR KÜÇÜKYILDIRIM A105 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2071', '.02 MİNE USLU UYSAL A205 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2081', '.01 Halil ÖZER A415 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2091', '.03 ÖZGEN AÇIKGÖZ A107 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2101', '.02 MEHMET SAFA BODUR A210 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2112', '.01 ABDÜLKERİM OKBAZ A308 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3182', '.01 Cihan DEMİR A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3201', '.01 Dr.Öğretim Üyesi SERKAN ERDEM A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3301', '.01 Ali PINARBAŞI A416 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3471', '.01 LEVENT YÜKSEK B401 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4391', '.01 Meral BAYRAKTAR A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4571', '.01 ÖZGÜN BALCI A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4651', '.01 Ahmet Selim DALKILIÇ A211 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK2142', '.01 NURULLAH KAYACI A319 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3151', '.01 Hasan Hüseyin ERDEM E202 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3431', '.01 ALİ SERDAR VANLI A406 (Yıldız)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3561', '.01 Tarkan SANDALCI B103 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3681', '.01 Ahmet Selim DALKILIÇ A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4422', '.01 Dr.Öğretim Üyesi FATİH SORGULU A205 (Yıldız)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4591', '.01 Ahmet Selim DALKILIÇ A406 (Yıldız)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4801', '.01 Nuri Alpay KÜREKCİ A406 (Yıldız)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1501', 'Analiz 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1511', 'Programlama Dilleri 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1551', 'İş Sağlığı ve Güvenliği 1 ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM1561', 'Matematik Mühendisliğine Giriş ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2501', 'İleri Analiz 1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2511', 'Algoritmalar ve Veri Yapıları ()', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2521', 'Nümerik Analiz I', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2531', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3611', 'Matematik Tarihi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3511', 'Bilgisayar Tasarımı / MTM3671 Çizge Kur. Ve Alg. MTM3591 Bulanık Mantık', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3551', 'İntegral Dön./ MTM3661 Mat. Lojik / MTM3721 Soyut Mat. MTM3531 Özel Fonksiyonlar (2G)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3641', 'Bilgisayar Des. Mat. Hesap. / MTM3681 Fourier Analizi MTM3601 Nümerik Analiz 2 ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3651', 'İstatistik', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3691', 'Lineer Programlama Teorisi ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3701', 'Mekanik 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4501', 'Yöneylem Araştırması ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4641', 'Veri Madenciliğine Giriş (2G) MTM4681 Mobil Programlama', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM4661', 'Nesneye Yön. İleri Prog. / MTM4591 Elastisite Teo. MTM4581 Oyunlar Teorisine Giriş ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4691', 'Bilg. Tab. Öğr. Sistemler / MTM4541 Dinamik MTM4571 Müh. Prob. Matematiksel Mod. ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4711', 'Matematiksel Modelleme ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/Career Counseling F.KAYA KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1911', 'Statistics B.C.FİLİZ ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'ITB1000', 'Sosyal Seçmeli Dersi', 2, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('MET', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/Career Counseling F.KAYA KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'MSE1911', 'Statistics B.C.FİLİZ ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET_ENG', 'ITB1000', 'Social Elective Course', 2, 1, 3, 3, 'Sosyal Seçmeli Havuzu', 0, None), 
    ('MET_ENG', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET_ENG', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1801', '| Gr01 İş Sağlığı ve Güvenliği Öğr. Gör. Dr. Gökçe Sönmez', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT1821', '| Gr01 Mekatronik Müh. Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1111', '| Gr02', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1831', '| Gr02 Lab 1 - Atölye ve İmalat', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2141', '| Gr01 Analog Elektronik Dr. Öğr. Üyesi Onurcan Şahin Yıldız - Oditoryum', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2161', '| Gr01', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2412', '| Gr01 Mühendisler için İstatistik Dr. Öğr. Üyesi Salih Obut A308', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2831', '| Gr01 Lab 2 - Elektrik ve Elektronik', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2151', '| Gr02 Nesneye Yönelik Programlama Dr. Öğr. Üyesi Ertuğrul', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1320', 'Lineer Cebir', 1, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1011', 'Yapay Zekanın Temelleri', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1021', 'Programlamaya Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1041', 'İş Sağlığı ve Güvenliği 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1042', 'İş Sağlığı ve Güvenliği 2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2021', 'Yazılım Mühendisliğinin İlkeleri', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2031', 'Veri Yapıları ve Algoritmalar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2042', 'Lojik ve Mikroişlemciler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2061', 'İstatistik ve Olasılık', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'TDB1031', 'Türkçe 1', 3, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2002', 'Genel Staj (STAJ) - Öğr. Gör. Dr. Fettah Kıran', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3011', 'Doğal Dil İşleme', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3012', 'Derin Öğrenmeye Giriş', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3021', 'Algoritma Analizi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3031', 'Bilgisayarla Görü', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 0, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
]

def seed_all():
    init_db()
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # Add days column if missing
    try:
        c.execute("ALTER TABLE courses ADD COLUMN days TEXT")
    except Exception:
        pass
    # Only seed if empty
    c.execute("SELECT COUNT(*) FROM courses")
    count = c.fetchone()[0]
    if count > 0:
        print(f"DB already has {count} courses, skipping seed.")
        conn.close()
        return
    c.executemany(
        "INSERT INTO courses (department_code, code, name, year, is_elective, credits, ects, instructor, is_online, days) VALUES (?,?,?,?,?,?,?,?,?,?)",
        ALL_COURSES
    )
    conn.commit()
    conn.close()
    print(f"Seeded {len(ALL_COURSES)} courses into DB.")

if __name__ == "__main__":
    seed_all()