# -*- coding: utf-8 -*-
# Auto-generated seed file - contains all 555 YTU courses
import sqlite3
from database import DB_PATH, init_db

ALL_COURSES = [
    ('BIO', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM1201', 'Introduction to Bioengineering Dr. Cem Özel BYM4211 Tissue Engineering Mehmet Murat Özmen, Emrah Şefik Abamor', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'KIM1170', 'Genel Kimya', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Perşembe'), 
    ('BIO', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM2071', 'Mass and Energy Balances Doç Dr. F. Tuğçe Şenberber Dumanl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM2101', 'Basic Principles in Molecular Biology Prof. Dr. Musa Türker BYM3501 Entrepreneurship and Project Management Dr. Selcen Ar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM2131', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM2321', 'Biochemistry in Bioengineering Doç. Dr. Murat Topuzoğullar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('BIO', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'BYM3031', 'Biomaterials Prof. Dr. Mehmet Murat Özmen BYM4381 Immunology Doç. Dr. Emrah Şefik Abamor', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM3321', 'Cell Culture Systems () Doç. Dr. Emrah Şefik Abamor BYM3601 Biosensors Dr. Mustafa Niğde ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'BYM3401', 'Separation Processes in Bioengineering Doç. Dr. Murat Topuzoğullar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Perşembe'), 
    ('BIO', 'BYM3511', 'Genetics Engineering Laboratory Prof. Dr. Dilek Bal', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM3521', 'Bioinstrumental Techniques Doç. Dr. Esma Özerol () BYM3531 Biomedical Electronics Prof. Dr. Ayhan Bingölbali () BYM3311 Introduction to Bioinformatics Dr. Öğr. Üyesi Hatice Büşra Lüleci (-A) BYM3361 Genetic Concepts Doç. Dr. Azade Attar ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM3921', 'Heat and Mass Transfer in Bioeng Doç. Dr. Benan İnan MES-4 BYM4801 Artificial Organs Doç. Dr. Azade Attar -A', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'BYM4721', 'Nanotechnology in Bioengineering Dr. Pelin Pelit Aray', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM4741', 'Bioprocess engineering Doç. Dr. Benan İnan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BLM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'BLM1011', 'Bilgisayar Bilimlerine Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM1991', 'İş Sağlığı ve Güvenliği 1', 1, 0, 1, 1, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'BLM2011', 'İstatistik ve Olasılık Hesabı', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2012', 'Nesneye Yönelik Programlama', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2521', 'Ayrık Matematik', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2611', 'Lojik Devreler', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2642', 'Bilgisayar Mühendisliği İçin Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'RAMI2026', 'BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ HAFTALIK DERS PROG-2027 Eğitim-Öğretim Yılı GÜZ Yarıyılı', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3011', 'İşletim Sistemleri', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3021', 'Algoritma Analizi', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3041', 'Veritabanı Yönetimi', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3042', 'Seminer ve Meslek Etiği', 3, 0, 1, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3061', 'Mikroişlemci Sistemleri', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3120', 'Bilgisayar Ağları ve Güvenliği', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3730', 'Blokzincir Temelleri ve Uygulamaları', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3010', 'Bilgisayar Mühendisliği Projesi', 4, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4011', 'Bilişim Sistemleri Güvenliği', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4021', 'Gömülü Sistemler ve Yapay Zeka', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4140', 'Kablosuz Mobil Ağlar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4800', 'Veri Madenciliğine Giriş', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM9000', 'Bitirme Çalışması', 4, 0, 4, 10, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BME4991', 'Multidisciplinary Design Project', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME1101', 'Introduction to Biomedical Engineering', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME1901', 'Introductory Computer Sciences', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5000', 'Yüksek Lisans Tezi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5003', 'Uzmanlık Alan Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5004', 'Research Methods and Scientific Ethics Classroom: C023', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5007', 'Applied Machine Learning Classroom: D011', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5009', 'Nanomaterials for Medical Applications Classroom: C151', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5014', 'Deep Learning Classroom: C151', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'KIM1170', 'Genel Kimya', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BMD', 'BME2011', 'Occupational Health and Safety', 2, 0, 1, 1, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2303', 'Circuit Theory', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2901', 'Biochemistry Laboratory', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2911', 'Introduction to Human Anatomy & Physiology Classroom: BB06(Amfi)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3161', 'Biosignal Processing', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3170', 'Medical Informatics Classroom: D011', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3310', 'System Identification', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3315', 'Analog Electronics Lab', 3, 0, 2, 4, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3323', 'Introduction to', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3325', 'Logic Design Lab.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3330', 'Biolectromagnetism', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3570', 'Biosensors', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3600', 'Biyomedikal Mühendisliğinde Seçmeli Ders 1', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3711', 'Biothermodynamics', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3921', 'Biomechanics 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4120', 'Biomedical Image Processing', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4142', 'Physiological Control Systems', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4370', 'Artificial Organs & Life Support Systems Classroom:', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4580', 'Genetic Engineering Classroom:D011', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4600', 'Biofluid Dynamics', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4901', 'Engineering Design', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4903', 'Medical Imaging Classroom:', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4991', 'Multidisciplinary Design Project', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM1011', 'EHM Giriş Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM1041', 'İş Sağl', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM1051', 'Algoritma Tasar', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Çarşamba'), 
    ('EHM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM2121', 'Devre ve Sistem Analizi Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2131', 'Elektromagnetik Alan Teorisi Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM2141', 'Lojik Devreler Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'EHM2161', 'Say', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM2171', 'Elektrik Devre Temelleri Laboratuvar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2191', 'Mühendislik Matematiği 2 Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'MDB2051', 'İngilizce Okuma ve Konuşma Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3111', 'Elektronik Devreler 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'EHM3121', 'Mikrodalga 1 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM3122', 'Haberleşme 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3131', 'Haberleşme 1 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3141', 'Mikroişlemci Sistemleri Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM3151', 'Elektronik Devreler 1 Laboratuvar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3181', 'Say', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM3731', 'Haberleşme Ağlar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM3741', 'Gömülü Sistemlerde Makine Öğrenmesi (TR) Murat Taşk', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4150', 'Gömülü Sistemlerde Donan', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4200', 'Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4260', 'Veri Haberleşmesi (ING) Tansal Güçlüoğlu B023 09.00 Pazartesi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4270', 'Hücresel Haberleşme Sistemleri 1 (ING) Shahen Shah B153 13.00', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4300', 'Fiber Optiğe Giriş (TR) Fikret Tokan B025 09.00 Sal', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4330', 'Optik Haberleşme Sistemleri (TR) Özlem Ünverdi B152 13.00', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4370', 'Mikroişlemcili Sistem Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4460', 'Uydu Haberleşmesinin Temelleri (ING) Ufuk Sakarya B153 09.00 Perşembe', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4830', 'Programlanabilir Lojik Devre Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4840', 'Görüntü İşleme Gr', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4880', 'Elektronik Savunma Sistemlerine Giriş (TR) Ahmet Serdar Türk B023 13.30', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4991', 'Çok Disiplinli Tasar', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM1071', 'ELM1071 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('ELK', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('ELK', 'ELM2010', 'ELM2010 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2040', 'ELM2040 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2061', 'ELM2061 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM2081', 'ELM2081 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2090', 'ELM2090 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2110', 'ELM2110 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2111', 'ELM2111 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2121', 'ELM2121 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2130', 'ELM2130 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2140', 'ELM2140 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2142', 'ELM2142 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi, Salı'), 
    ('ELK', 'ELM3001', 'ELM3001 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3071', 'ELM3071 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3081', 'ELM3081 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'ELM3301', 'G1 C336', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3302', 'G4 Ayd L', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('ELK', 'ELM3762', 'ELM3762 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4040', 'ELM4040 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4041', 'G1 Elk Mak L', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'ELM4045', 'ELM4045 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4050', 'ELM4050 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4051', 'ELM4051 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4060', 'ELM4060 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4071', 'ELM4071 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4080', 'ELM4080 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4090', 'ELM4090 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4250', 'ELM4250 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4270', 'ELM4270 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4290', 'ELM4290 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4301', 'ELM4301 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4401', 'G1 YA Lab', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4411', 'G1 YES Lab', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4421', 'G1 Tesis L', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4612', 'G1 Elk Mak L', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4622', 'G1 Guc L', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4750', 'ELM4750 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4810', 'ELM4810 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4820', 'ELM4820 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4980', 'ELM4980 Dersi', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1151', 'Bilgisayar Programlama 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1911', 'İş Sağlığı ve Güvenliği 1', 1, 0, 1, 1, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1991', 'Endüstri Mühendisliğine Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2151', 'Bilgisayar Programlama 2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2961', 'Ekonomi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2991', 'Probability Gr1 A310 Prof. Dr. Selin SONER KARA', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2995', 'Üretim Yöntemleri', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END3401', 'İş Etüdü ve Çalışma Standardı', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3455', 'Pazarlama Yönetimi (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3760', 'Çizelgeleme Yöntemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3770', 'Stokastik Süreçler (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3875', 'Heuristic Optimization Methods Gr1 A308 Öğr. Gör. Dr. K. Büşra YILMAZER KAYA', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3961', 'Sistem Analizi ve Tasarımı', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3965', 'Applied Artificial Learning Gr1 A319 Dr. Öğr. Üyesi Serkan SALTÜRK', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3975', 'Yapay Zeka ve İşletme Uygulamaları (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3981', 'Engineering Economics Gr1 B401 Dr. Öğr. Üyesi Esra İLBAHAR', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3991', 'Yöneylem Araştırması 2', 3, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3995', 'Kalite Mühendisliği', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH3200', 'Savunma Sanayide Mühendislik Malzemeleri ve Stratejik Tedarik Zinciri Yönetimi Gr1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MTH3446', 'Mikro Fly ERP ile Dijital Üretim Yönetimi Gr1 A205', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4000', 'Graduation Thesis All Groups', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4370', 'Stratejik Yönetim (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4393', 'Risk Yönetimi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4420', 'Proje Yönetimi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4480', 'İşletmelerde Verimlilik Yönetimi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4651', 'Toplam Kalite Yönetimi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4661', 'Endüstri Mühendisliği Tasarımı Projesi', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4665', 'Finansal Yönetim (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4810', 'Envanter Modelleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4830', 'Yalın Üretim Sistemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4971', 'Facilities Planning and Control Gr1 B405 Doç. Dr. Doğan ÖZGEN', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4985', 'İş Hukuku (Seçmeli)', 4, 1, 2, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4990', 'İstatistiksel Kalite Kontrol', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4995', 'Ajan Tabanlı Modelleme Ve Simülasyon (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MFK4991', 'Çok Disiplinli Tasarım Projesi', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH4800', 'Innovation Campus Artificial Intelligence (Samsung) Gr1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('GDA', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('GDA', 'GDM1301', 'GDM1301 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM1303', 'GDM1303 Dersi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('GDA', 'GDM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM1170', 'Genel Kimya', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('GDA', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('GDA', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM2091', 'Kütle ve Enerji Denklikleri Dr. Öğr. Üyesi Fatih BOZKURT GDM4595 İnsan Merkezli Yapay Zeka Dr. Öğr. Üyesi Duygu ÖZMEN', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM2112', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2172', 'GDM2172 Dersi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2181', 'Genel Mikrobiyoloji Doç. Dr. Banu METİN GDM3306 Fermentasyon Teknolojisi Prof. Dr. Muhammet ARICI GDM4111 G', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM2301', 'Analitik Kimya (', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM3211', 'Enstrümental Analizler (Lab) Doç. Dr. Nur ÇEBİ', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('GDA', 'GDM3231', 'GDM3231 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM3261', 'Reaksiyon Kinetiği Prof. Dr. Ömer Said TOKER', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM3271', 'Girişimcilik ve Proje Yönetimi Dr. Öğr. Üyesi Öznur SAROĞLU', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM3301', 'GDM3301 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'GDM3303', 'GDM3303 Dersi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM4121', 'GDM4121 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'GDM4301', 'GDM4301 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM4303', 'Su Ürünleri İşleme Teknolojisi Doç. Dr. Şenol KÖSE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4305', 'Süt ve Ürünleri Teknolojisi Prof. Dr. Osman SAĞDIÇ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4307', 'Et ve Ürünleri Teknolojisi (EN) Doç. Dr. Ruşen METİN YILDIRIM', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM4309', 'GDM4309 Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('KIM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KIM1501', 'Genel Kimya 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KIM1501', 'Genel Kimya 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM1041', 'Int. to Chem. Eng. D.Dinçer (KMB 210) İ.Küçük (KME 306)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM1041', 'Kimya Müh.Giriş İ. Doymaz (KMB 210)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB2631', 'Mühendisler İçin İstatistik ve Olasılık', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2601', 'Occ. Health & Safety-1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2601', 'İş Sağlığı ve Güv. 1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2611', 'Chem. Eng.Calc.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2611', 'Kimya Müh. Hesap.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2621', 'Phy. Chem. For Eng. T. Gösterişli (KMB 322) F. Dumanli (KMB 314)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2621', 'Müh. için Fiz. Kimya S. Deniz (KMB 316) Y. Kalpaklı (KME 306)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2631', 'Probability and Statistics for Engineers', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2631', 'Probability and Statistics for', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB3631', 'Artificial Intelligence for Chemical Engineers (M. A. İnsel) (KMB 306)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB3631', 'Artificial Intelligence for', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3501', 'Ent. & Project Man.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3501', 'Giriş. ve Proje Yön.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3511', 'Numerical Analysis', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3511', 'Sayısal Analiz N. Acaralı (KMB 322)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3521', 'Heat Transfer in Chem. Eng.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3521', 'Kimya Müh. Isı Aktarımı', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3531', 'Chemical Eng. Thermo. 2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3531', 'Kimya Müh. Termodinamiği 2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3541', 'Mass Transfer', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3541', 'Kütle Aktarımı İ. Özgündüz (KMB 218)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3551', 'Env. Technology J. Gülen', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3551', 'Env. Technology J. Gülen', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3561', 'UMS Technical Communication (E. Akyol)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3561', 'UMS Teknik İletişim (N. Tuğrul)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3571', 'Yakıtlar ve Yakıt Tek. (O. İsmail) KMM3581 Enerji Tasarrufu (S. Keyf)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3591', 'Analysis Methods in Chemical Industry E. Derun', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3591', 'Analysis Methods in Chemical', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3611', 'Kimya End. Kalite Kontrol (Y. Kalpaklı)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4000', 'Graduation Thesis', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4000', 'Bitirme Çalışması', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4611', 'Pro. Des. in Chemical Eng. I', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4611', 'Kimya Müh. Proses Tasarımı 1 Y. Salt (KMB 210), İ. Salt (KMB 218)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4621', 'Chemical Reactor Design', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4621', 'Kimyasal Reaktör Tasarımı B. Özbek (KMB 314) E. Yılmaz (KME 306) ENG açılacak', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4631', 'Process Dynamics and Control E. Yılmaz (KMB 314) E. Kıpçak (KMB 218)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4631', 'Proses Dinamiği ve Kontrolü M. Akgün (KMB 316)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4641', 'W. Recyc. J. Gülen KMM4691 Bioseperation (M. Yılmaz)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4641', 'Atık Geri Dön. N. Tuğrul', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4651', 'Bio. E. Fund. (B. Özbek)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4651', 'Bio. E. Fund. (B. Özbek)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4661', 'Gıda Tek. Temel İş. (İ. Doymaz)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4671', 'Chemical Engineering Economics T. U. Gösterişli', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4671', 'Chemical Engineering Economics Gr 2 T. U. Gösterişli', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4681', 'Pol. Üretimi ve', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4711', 'Elektro.', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4721', 'Opt. in Chem. Eng. H. Sadıkoğlu', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4721', 'Opt. in Chem. Eng. H. Sadıkoğlu', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4731', 'Memb. ve', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4741', 'Yeni ve', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4751', 'Calc. in Multi-Component Sep. Systems', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4751', 'Calc. in Multi-Component Sep.', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1051', 'Teknik Resim ve Bilgisayar Destekli Çizim', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1061', 'Makine Mühendisliğine Giriş', 1, 0, 2, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1062', 'Mühendislik Etiği ve Kariyer Planlama', 1, 0, 1, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1071', 'Makine Elemanları Çizimi', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1072', 'Bilgisayar Destekli Modelleme', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK2011', 'Statik & Mukavemet', 2, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2061', 'İmalat İşlemleri', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2071', 'Termodinamik 1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2081', 'Termodinamik 2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2091', 'Dinamik', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2101', 'Akışkanlar Mekaniği 1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2112', 'Akışkanlar Mekaniği 2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2142', 'Malzeme Bilimi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2212', 'Mekanizma Tekniği', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2482', 'Nümerik Yöntemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK3071', 'Isı Geçişi', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3091', 'Makine Elemanları 1', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3151', 'Makine Dinamiği ve Titreşimler', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3182', 'Makine Elemanları 2', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3191', 'Otomatik Kontrol', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3201', 'Isıtma ve Havalandırma Sistemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3271', 'Motorlar ve Güç Sistemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3281', 'Taşıt Mekaniği (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3291', 'Hidrolik ve Pnömatik Sistemler (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3301', 'Yenilenebilir Enerji Kaynakları (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3391', 'Talaşlı İmalat Yöntemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3401', 'Kalıp Tasarımı ve İmalatı (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3431', 'CAD/CAM Sistemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3441', 'Kaynak Teknolojisi (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3461', 'Ürün Tasarımı ve Geliştirme (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3471', 'Triboloji ve Aşınma (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3561', 'Mühendislik Deneyleri', 3, 0, 2, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3652', 'Staj 1', 3, 0, 1, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3671', 'İçten Yanmalı Motorlar (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3681', 'Soğutma Tekniği (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3691', 'Güneş Enerjisi Sistemleri (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4072', 'Termik Santraller (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4092', 'Buhar Kazanları Tasarımı (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4261', 'Isı Değiştiricileri Tasarımı (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4291', 'Gaz Türbinleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4391', 'Pompa ve Kompresörler (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4401', 'Nükleer Enerjiye Giriş (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4422', 'Yapay Zeka Ve Makine Uygulamaları (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4451', 'Klima Sistemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4471', 'Yenilikçi Enerji Teknolojileri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4472', 'Enerji Depolama Sistemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4482', 'Batarya Teknolojileri ve Yönetimi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4491', 'Hesaplamalı Akışkanlar Dinamiği (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4541', 'Kompozit Malzemeler (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4571', 'Sonlu Elemanlar Yöntemi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4591', 'Mikro Ve Nano Isı Geçişi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4595', 'Optimizasyon Yöntemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4601', 'Tahribatsız Muayene Yöntemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4651', 'İki Fazlı Akışlar (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4801', 'Havacılık Ve Uzay Sistemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4891', 'Makine Mühendisliği Tasarımı 1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4921', 'Makine Mühendisliği Tasarımı 2', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4931', 'Bitirme Çalışması 1', 4, 0, 4, 8, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4933', 'Bitirme Çalışması 2', 4, 0, 4, 8, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4941', 'Uzmanlık Projesi (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1501', 'Analiz 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1511', 'Programlama Dilleri 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1551', 'İş Sağlığı ve Güvenliği 1 ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM1561', 'Matematik Mühendisliğine Giriş ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2501', 'İleri Analiz 1', 2, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2511', 'Algoritmalar ve Veri Yapıları ()', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2521', 'Nümerik Analiz I', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2531', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3511', 'Bilgisayar Tasarımı / MTM3671 Çizge Kur. Ve Alg. MTM3591 Bulanık Mantık', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3551', 'İntegral Dön./ MTM3661 Mat. Lojik / MTM3721 Soyut Mat. MTM3531 Özel Fonksiyonlar (2G)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3611', 'Matematik Tarihi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3641', 'Bilgisayar Des. Mat. Hesap. / MTM3681 Fourier Analizi MTM3601 Nümerik Analiz 2 ()', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3651', 'İstatistik', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3691', 'Lineer Programlama Teorisi (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3701', 'Mekanik 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM4501', 'Yöneylem Araştırması ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4641', 'Veri Madenciliğine Giriş (2G) MTM4681 Mobil Programlama', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM4661', 'Nesneye Yön. İleri Prog. / MTM4591 Elastisite Teo. MTM4581 Oyunlar Teorisine Giriş ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4691', 'Bilg. Tab. Öğr. Sistemler / MTM4541 Dinamik MTM4571 Müh. Prob. Matematiksel Mod. ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4711', 'Matematiksel Modelleme ()', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/Career Counseling F.KAYA KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/Career Counseling F.KAYA KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1911', 'Statistics B.C.FİLİZ ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'MSE1911', 'Statistics B.C.FİLİZ ()', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2091', 'Mass and Energy Balance S.AVCIOĞLU KMB217', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2091', 'Mass and Energy Balance S.AVCIOĞLU KMB217', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2101', 'Applied Engineering Mathematics F.AKYOL KMB329-B', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2101', 'Applied Engineering Mathematics F.AKYOL KMB329-B', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2711', 'Materials Science G.1 F.KAYA KMB317', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2711', 'Materials Science G.1 F.KAYA KMB317', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2911', 'Statics and Strength of Materials', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2911', 'Statics and Strength of Materials', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2921', 'Thermodynamics of Materials A.E.ERSUNDU KMB313', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2921', 'Thermodynamics of Materials A.E.ERSUNDU KMB313', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2941', 'OCCUPATIONAL HEALTH AND SAFETY 1 M.YILMAZ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'MSE2941', 'OCCUPATIONAL HEALTH AND SAFETY 1 M.YILMAZ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'KMM3501', 'ENTREPRENEURSHIP AND PROJECT MANAGEMENT ON-LINE A.AYDINOĞLU', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'KMM3501', 'ENTREPRENEURSHIP AND PROJECT MANAGEMENT ON-LINE A.AYDINOĞLU', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3072', '(MES4) Physical Properties of Materials F.AKYOL KMB312', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3072', '(MES4) Physical Properties of Materials F.AKYOL KMB312', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3271', '(MES1) Metrology and Calibration N.DUYGULU KMB317', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3271', '(MES1) Metrology and Calibration N.DUYGULU KMB317', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3381', 'Transport Phenomena', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3381', 'Transport Phenomena', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3401', '(MES3) Hydrometallurgy M.GENÇTEN KMB313', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3401', '(MES3) Hydrometallurgy M.GENÇTEN KMB313', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3411', '(MES3) Glass Technology A.E.ERSUNDU KMB317', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3411', '(MES3) Glass Technology A.E.ERSUNDU KMB317', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3421', '(MES3) Non-Ferrous Metals Metallurgy B.BİROL KMB217', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3421', '(MES3) Non-Ferrous Metals Metallurgy B.BİROL KMB217', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3501', 'Welding Technology (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3501', 'Welding Technology (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3521', '(MES1) MANUFACTURING METHODS OF CERAMICS B.ÇİÇEK KMB217', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3521', '(MES1) MANUFACTURING METHODS OF CERAMICS B.ÇİÇEK KMB217', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3531', 'Machine Elements for Engineers (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3531', 'Machine Elements for Engineers (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3571', '(MES1) Electrometallurgy J.H.ÖZDEMİR KME307', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3571', '(MES1) Electrometallurgy J.H.ÖZDEMİR KME307', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3581', '(MES1) Advanced Ceramics G.Ş.FRANCİ KME307', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3581', '(MES1) Advanced Ceramics G.Ş.FRANCİ KME307', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3591', 'Medical Device Regulations (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3591', 'Medical Device Regulations (Seçmeli)', 3, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3901', 'Mechanical Properties of Materials', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3901', 'Mechanical Properties of Materials', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3911', 'Principles of Solidification', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3911', 'Principles of Solidification', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3941', 'Iron and Steelmaking B.BİROL KMB313', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3941', 'Iron and Steelmaking B.BİROL KMB313', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4071', '(MES3) Biomedical Materials N.K.SUMAMA KMB317', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4071', '(MES3) Biomedical Materials N.K.SUMAMA KMB317', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4081', '(MES3) Nano Materials N.K.SUMAMA KMB217', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4081', '(MES3) Nano Materials N.K.SUMAMA KMB217', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4121', 'Material Production Laboratory 1 S.AVCIOĞLU', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4121', 'Material Production Laboratory 1 S.AVCIOĞLU', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4131', '(ÜMS) Material World (Univ.Prof.Electiv) B.Ö.KISASÖZ (Metallurgical and Materials Engineering students have to take the equivalent course from other departments) KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4131', '(ÜMS) Material World (Univ.Prof.Electiv) B.Ö.KISASÖZ (Metallurgical and Materials Engineering students have to take the equivalent course from other departments) KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4591', '(MES2) Interdisciplinary Design Application in Materials Technologies', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4591', '(MES2) Interdisciplinary Design Application in Materials Technologies', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4621', 'Metallurgy Kinetics', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4621', 'Metallurgy Kinetics', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4631', 'Corrosion and Prevention O.K. ÖZDEMİR KMB313', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4631', 'Corrosion and Prevention O.K. ÖZDEMİR KMB313', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4831', '(MES2) DESIGN APPLICATIONS IN METALLURGICAL PRODUCTION', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4831', '(MES2) DESIGN APPLICATIONS IN METALLURGICAL PRODUCTION', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4841', '(MES2) DESIGN APPLICATIONS IN MATERIAL TECHNOLOGIES', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4841', '(MES2) DESIGN APPLICATIONS IN MATERIAL TECHNOLOGIES', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4851', '(MES2) DESIGN APPLICATIONS IN CERAMIC TECHNOLOGIES', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4851', '(MES2) DESIGN APPLICATIONS IN CERAMIC TECHNOLOGIES', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4861', '(MES1) MATERIALS FOR DEFENCE INDUSTRY B.ÇİÇEK KMB303', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4861', '(MES1) MATERIALS FOR DEFENCE INDUSTRY B.ÇİÇEK KMB303', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4881', '(MES1) Polymer Processing H.BERBER KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4881', '(MES1) Polymer Processing B.Ö.KISASÖZ KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4891', 'Automotive Materials (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4891', 'Automotive Materials (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4911', 'Functional Materials (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4911', 'Functional Materials (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4931', 'Ferroalloy Production Methods (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4931', 'Ferroalloy Production Methods (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4941', '(MES1) Advanced Structural Steels A.KISASÖZ KMB317', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4941', '(MES1) Advanced Structural Steels A.KISASÖZ KMB317', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4951', '(MES1) Aerospace and Aviation Materials A.SAĞIN KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4951', '(MES1) Aerospace and Aviation Materials A.SAĞIN KME307', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1111', 'Bilgisayar Programlama', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1801', 'İş Sağlığı ve Güvenliği 1', 1, 0, 1, 1, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT1821', 'Mekatronik Mühendisliğine Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1831', 'Laboratuvar 1 - Atölye ve İmalat', 1, 0, 2, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5001', '| Gr01 Yüksek Lisans Seminer Dr. Öğr. Üyesi Kemal Mert Doğan A108', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5112', '| Gr01 Linear System Theory Prof. Dr. Cüneyt Yılmaz A113', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5115', '| Gr01 Systems Engineering in Mechatronics Doç. Dr. Hüseyin Üvet', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5120', '| Gr01', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5121', '| Gr01', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5125', '| Gr01', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5127', '| Gr01 Ürün Tasarımı ve Girişimcilik Prof. Dr. Ahmet Koyun', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6001', '| Gr01 Yüksek Lisans Seminer Dr. Öğr. Üyesi Kemal Mert Doğan A108', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6107', '| Gr01 Mekatronikte Yapay Zeka Prof. Dr. Erhan Akdoğan A410', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6108', '| Gr01 Mekatronikte Özel Konular Dr. Öğr. Üyesi Mehmet İşcan', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT6116', '| Gr01 Mühendislik Matematiği 2 Dr. Öğr. Üyesi Parisa Heidarnejad', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6119', '| Gr01 Newtonyen Olmayan Akışkanlar Doç. Dr. Hatice Mercan', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6125', '| Gr01 Fuzzy Modeling and Control Prof. Dr. Cenk Ulu A416', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT2411', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2141', 'Analog Elektronik', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2151', 'Nesneye Yönelik Programlama', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2161', 'Lojik Devre Tasarımı', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2412', 'Mühendisler İçin İstatistik', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2831', 'Laboratuvar 2 - Elektrik ve Elektronik', 2, 0, 2, 3, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3411', 'Akışkanlar Mekaniği', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3413', 'Isı Geçişi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3421', 'İşaretler ve Sistemler', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3801', 'Staj 1', 3, 0, 1, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3811', 'Mikroişlemciler ve Programlanması', 3, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3821', 'Makine Elemanları', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3841', 'Sayısal Yöntemler', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MFK4991', 'Çok Disiplinli Tasarım Projesi', 4, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT4111', 'Bitirme Çalışması', 4, 0, 4, 8, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4403', 'Mekatronik Sistem Entegrasyonu (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4441', 'İmalat Yöntemleri (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4443', 'A114 ─────────── | Gr01 Proses Tekniği Dr. Parisa Heidarnejad A211', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4451', '| Gr01 Elektriksel Tahrik Sistemleri Prof. Dr. Cenk Ulu A403', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4453', '| Gr01 Yeni Nesil Elektrik Motorları Doç. Dr. Muhammet Garip B403', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4461', '| Gr01 Proje Yönetimi Doç. Dr. Hüseyin Üvet B402 ─────────── MKT4463 | Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4802', '| Gr01 Lab 4 - Motorlar ve Sürücüler', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4820', 'Otonom Sistemler (Seçmeli)', 4, 1, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4830', '| Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4831', '| Gr01 Robot Mühendisliği Prof. Dr. Vasfi Emre Ömürlü A416', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4837', '| Gr01 Optomekatroniğe Giriş Dr. Öğr. Üyesi Onurcan Şahin', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4848', '| Gr01 Pekiştirmeli Öğrenme Dr. Öğr. Üyesi Mehmet İşcan A105 (%30 -%100)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MTH4701', '| Gr01 Elektrikli Araçlarda Güç Dönüşümü Dr. Fatih Eroğlu', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'ATA1031', 'Atatürk İlkeleri ve İnkılap Tarihi 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'FIZ1001', 'Fizik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1071', 'Matematik 1', 1, 0, 4, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MDB1031', 'İleri İngilizce 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'TDB1031', 'Türkçe 1', 1, 0, 2, 2, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1011', 'Yapay Zekanın Temelleri', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1021', 'Programlamaya Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1041', 'İş Sağlığı ve Güvenliği 1', 1, 0, 1, 1, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1042', 'İş Sağlığı ve Güvenliği 2', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'RAMI2026', 'YAPAY ZEKA VE VERİ MÜHENDİSLİĞİ BÖLÜMÜ HAFTALIK DERS PROG-2027 Eğitim-Öğretim Yılı / GÜZ Yarıyılı', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2002', 'Genel Staj (STAJ) - Öğr. Gör. Dr. Fettah Kıran', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2021', 'Yazılım Mühendisliğinin İlkeleri', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2031', 'Veri Yapıları ve Algoritmalar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2042', 'Lojik ve Mikroişlemciler', 2, 0, 3, 6, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2061', 'İstatistik ve Olasılık', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3011', 'Doğal Dil İşleme', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3012', 'Derin Öğrenmeye Giriş', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3021', 'Algoritma Analizi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3031', 'Bilgisayarla Görü', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
]

def seed_all():
    init_db()
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # Add days column if missing
    try:
        c.execute("ALTER TABLE courses ADD COLUMN days TEXT")
    except Exception:
        pass
    # Only seed if empty
    c.execute("SELECT COUNT(*) FROM courses")
    count = c.fetchone()[0]
    if count > 0:
        print(f"DB already has {count} courses, skipping seed.")
        conn.close()
        return
    c.executemany(
        "INSERT INTO courses (department_code, code, name, year, is_elective, credits, ects, instructor, is_online, days) VALUES (?,?,?,?,?,?,?,?,?,?)",
        ALL_COURSES
    )
    conn.commit()
    conn.close()
    print(f"Seeded {len(ALL_COURSES)} courses into DB.")

if __name__ == "__main__":
    seed_all()