# -*- coding: utf-8 -*-
# Auto-generated seed file - contains all 555 YTU courses
import sqlite3
from database import DB_PATH, init_db

ALL_COURSES = [
    ('BIO', 'ATA1031', 'Atatürk İlkeleri ve İnk', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM1201', 'Introduction to Bioengineering Gr.2', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'FIZ1001', 'Physics 1 Gr.50, Gr. 51 Gr. 50', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'KIM1170', 'General Chemistry Gr.23 KMB-321 MES-4', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Perşembe'), 
    ('BIO', 'MAT1071', 'Mathematics 1 Gr.52 ONLINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'MDB1031', 'İleri İngilizce 1 Gr.28 KMB-318 BYM2321 Biochemistry in Bioe', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'TDB1031', 'Türkçe 1 ONLINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM2071', 'Mass and Energy Balances Gr.2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM2101', 'Basic Principles in Molecular Biology Gr.2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM2131', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM2321', 'Biochemistry in Bioengineering Gr.2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('BIO', 'MAT2411', 'Diferansiyel Denklemler Gr.51 ONLINE', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('BIO', 'BYM3031', 'Biomaterials Gr.2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('BIO', 'BYM3321', 'Cell Culture Systems Gr. 1 (KMB-315)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('BIO', 'BYM3401', 'Separation Processes in Bioengineering Gr.2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Perşembe'), 
    ('BIO', 'BYM3511', 'Genetics Engineering Laboratory Gr.2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM3521', 'Bioinstrumental Techniques Gr.1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BIO', 'BYM3921', 'Heat and Mass Transfer in Bioeng Gr.3', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('BIO', 'BYM4721', 'Nanotechnology in Bioengineering', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BIO', 'BYM4741', 'Bioprocess engineering  Gr. 2', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('BLM', 'BLM1011', 'Bilgisayar Bilimlerine Gir.', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM1991', 'İş Sağ. Güv. 1 Online', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'FIZ1001', 'Fizik 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MAT1071', 'Online', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'MAT1320', 'Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'MDB1031', 'İleri İngilizce I', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'RAMI2026', 'ELEKTRİK ELEKTRONİK FAKÜLTESİ BİLGİSAYAR MÜHENDİSLİĞİ BÖLÜMÜ', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2011', 'İst. ve Olasılık Hes.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2012', 'Nesneye Yön. Prog.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2521', 'Ayrık Matematik', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2611', 'Lojik Devreler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM2642', 'Bilg. Müh. İçin Diff. Denk.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3010', 'Bilgisayar Projesi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3011', 'İşletim Sistemleri', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3021', 'Algoritma Analizi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3041', 'Veritabanı Yönetimi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3042', 'Seminer ve Meslek Etiği', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3061', 'Mikroişl. Sist. ve Assmb. D', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM3730', 'Blokzincir Temelleri', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'TDB1031', 'Türkçe 1 Online', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'ATA1031', 'Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BLM', 'BLM3120', 'Bil.Er.Ar.Mot.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4011', 'Bilişim Sis. Güvenliği', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4021', 'Gömülü Sistemler', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4140', 'Kablosuz Mobil Ağlar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM4800', 'Veri Madenciliğine Giriş', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BLM9000', '(İng.) Bitirme Çalışması', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BLM', 'BME4991', 'BME4991 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME1101', 'Introduction to Biomedical Engineering', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME1901', 'Introductory Computer Sciences', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'FIZ1001', 'Physics 1 (Gr.48)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'KIM1170', 'General Chemistry (Gr.22)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1071', 'Mathematics 1 (Gr.55)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MDB1031', 'Advanced English 1 (Gr.33)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'TDB1031', 'Turkish Language 1 (Online)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('BMD', 'BME2011', 'Occupational Health And', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2303', 'Circuit Theory', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2901', 'Biochemistry Lab.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME2911', 'Introduction to Human Anatomy & Physiology Classroom: BB06(A', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT1320', 'Linear Algebra (Gr.32) (EEF-D-', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'MAT2411', 'Differential Equations (Gr.54)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'ATA1031', 'Principles of Atatürk and', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3161', 'Biosignal Processing', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3170', 'Medical Informatics Classroom: D011', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3310', 'System Identification', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3315', 'Analog Electronic Lab.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3323', 'Introduction to', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3325', 'Logic Design Lab.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3330', 'Biolectromagnetism', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3570', 'Biosensors', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3600', 'Biyomedikal Mühendisliğinde', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3711', 'Biothermodynamics', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME3921', 'Biomechanics 1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4120', 'Biomedical Image Processing', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4142', 'Physiological Control', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4370', 'Artificial Organs & Life Support Systems Classroom:', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4580', 'Genetic Engineering Classroom:D011', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4600', 'Fluid Dynamics Classroom:', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4901', 'Engineering Design', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4903', 'Medical Imaging Classroom:', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME4991', 'Multidisciplinary Design Project', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5000', 'Yüksek Lisans Tezi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5003', 'Uzmanlık Alan Dersi', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5004', 'Research Methods and Scientific Ethics Classroom: C023', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5007', 'Applied Machine Learning Classroom: D011', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5009', 'Nanomaterials for Medical Applications Classroom: C151', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('BMD', 'BME5014', 'Deep Learning Classroom: C151', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'ATA1031', 'Atatürk İlkeleri ve İnk', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM1011', 'EHM Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM1041', 'İş Sağl', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM1051', 'Algoritma Tasar', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'FIZ1001', 'Fizik 1 Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Çarşamba'), 
    ('EHM', 'MAT1071', 'Matematik 1 Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'MAT1320', 'Lineer Cebir Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'MDB1031', 'İleri İngilizce 1 Gr', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'TDB1031', 'Türkçe 1 B024 13.00', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM2121', 'Devre ve Sistem Analizi', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2131', 'Elektromagnetik Alan Teorisi Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Salı'), 
    ('EHM', 'EHM2141', 'Lojik Devreler Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('EHM', 'EHM2171', 'Elektrik Devre Temelleri Laboratuvar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM2191', 'Mühendislik Matematiği 2 Gr', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'MDB2051', 'İngilizce Okuma ve Konuşma', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3111', 'Elektronik Devreler 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe, Çarşamba'), 
    ('EHM', 'EHM3121', 'Mikrodalga 1                                  Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM3122', 'Haberleşme 2 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3131', 'Haberleşme 1 Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM3141', 'Mikroişlemci Sistemleri Gr', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM3151', 'Elektronik Devreler 1 Laboratuvar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM3731', 'Haberleşme Ağlar', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM3741', 'Gömülü Sistemlerde Makine Öğrenmesi (TR) Murat Taşk', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4150', 'Gömülü Sistemlerde Donan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4200', 'Tasar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4260', 'Veri Haberleşmesi (ING)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4270', 'Hücresel Haberleşme Sistemleri 1 (ING) Shahen Shah B153', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('EHM', 'EHM4300', 'Fiber Optiğe Giriş                                (TR) Fikre', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('EHM', 'EHM4330', 'Optik Haberleşme Sistemleri (TR)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4370', 'Mikroişlemcili Sistem Tasar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4460', 'Uydu Haberleşmesinin Temelleri (ING)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4830', 'Programlanabilir Lojik Devre Tasar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('EHM', 'EHM4840', 'Görüntü İşleme', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('EHM', 'EHM4880', 'Elektronik Savunma Sistemlerine Giriş (TR)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('EHM', 'EHM4991', 'Çok Disiplinli Tasar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM1071', 'ELM1071 Ders', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'FIZ1001', 'G21 C150', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('ELK', 'MAT1071', 'MAT1071 Ders', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'MAT1320', 'G14 C150', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MDB1031', 'MDB1031 Ders', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2040', 'ELM2040 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2061', 'ELM2061 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('ELK', 'ELM2081', 'ELM2081 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2111', 'ELM2111 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2130', 'ELM2130 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2142', 'ELM2142 Ders', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'MAT2411', 'G11 ONLINE', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi, Salı'), 
    ('ELK', 'TDB1031', 'G ONLINE', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('ELK', 'ELM2090', 'ELM2090 Ders', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2110', 'ELM2110 Ders', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2121', 'ELM2121 Ders', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2010', 'ELM2010 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM2140', 'ELM2140 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3001', 'ELM3001 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3071', 'ELM3071 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3081', 'ELM3081 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'ELM3301', 'G1 C336', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM3302', 'G4 Ayd L', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('ELK', 'ELM3762', 'ELM3762 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4040', 'ELM4040 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4041', 'G1 Elk Mak L', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('ELK', 'ELM4045', 'ELM4045 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4050', 'ELM4050 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4051', 'ELM4051 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4060', 'ELM4060 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4071', 'ELM4071 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4080', 'ELM4080 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4090', 'ELM4090 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4250', 'ELM4250 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4270', 'ELM4270 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4290', 'ELM4290 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4301', 'ELM4301 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4401', 'G1 YA Lab', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4411', 'G1 YES Lab', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4421', 'G1 Tesis L', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4612', 'G1 Elk Mak L', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4622', 'G1 Guc L', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4750', 'ELM4750 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('ELK', 'ELM4810', 'ELM4810 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4820', 'ELM4820 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('ELK', 'ELM4980', 'ELM4980 Ders', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'ATA1031', 'Principles of Atatürk and History of Modern Turkey 1 Gr 39 O', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1151', 'Computer Programming 1 Gr2 ONLINE Doç. Dr. Mert EDALI', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1911', 'Occupational Health and Safety 1 Gr1 ONLINE Arş. Gör. Dr. Me', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END1991', 'Introduction to Industrial Engineering Gr1 ODITORYUM Prof. D', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2995', 'Manufacturing Processes Gr1 A310 Doç. Dr. Tolga MERT', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3455', 'Pazarlama Gr1 A415 Öğr. Gör. Dr. Ufuk BÖLÜKBAŞ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3975', 'Artificial Intelligence Gr2 A313 Doç. Dr. Ali KARAŞAN', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4665', 'Financial Management Gr1 A205 Dr. Öğr. Üyesi Evrim HACIOĞLU ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4985', 'İş Hukuku Gr1 A107 Dr. Öğr. Üyesi Ahmet Reşat SARAOĞLU', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'FIZ1001', 'Physics 1 Gr 41 - Gr 42 DZ130-DZ131', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT1071', 'Mathematics 1 Gr 57 ONLINE', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MDB1031', 'Advanced English 1 Gr 21 A107', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH3200', 'Savunma Sanayide Mühendislik Malzemeleri ve Stratejik Tedari', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'TDB1031', 'Turkish Language 1 Gr 55 ONLINE', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2151', 'Computer Programming 2 Gr1 ONLINE Arş. Gör. Dr. Meryem Ezgi ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'END2961', 'Economics Gr1 B202 Prof. Dr. Feride GÖNEL', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END2991', 'Probability Gr1 A310 Prof. Dr. Selin SONER KARA', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3401', 'Work Methods and Measurements Gr1 A310 Prof. Dr. Alev TAŞKIN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3760', 'Scheduling Gr1 B201 Arş. Gör. Dr. Betül ÖZKAN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3770', 'Stochastic Processes Gr1 A210 Doç. Dr. Bora ÇEKYAY', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3875', 'Heuristic Optimization Methods Gr1 A308 Öğr. Gör. Dr. K. Büş', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3961', 'System Analysis Gr1 B402 Prof. Dr. Şükran ŞEKER', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3965', 'Applied Artificial Learning Gr1 A319 Dr. Öğr. Üyesi Serkan S', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3981', 'Engineering Economics Gr1 B401 Dr. Öğr. Üyesi Esra İLBAHAR', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3991', 'Operations Research 2 Gr1 A310 Doç. Dr. Vildan ÖZKIR', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END3995', 'Quality Engineering Gr2 A318 Arş. Gör. Dr. Aslıhan YILDIZ GÖ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4000', 'Graduation Thesis All Groups', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4370', 'Strategic Management Gr1 A113 Doç. Dr. Doğan ÖZGEN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4393', 'Risk Management Gr1 A113 Arş. Gör. Dr. Betül ÖZKAN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4420', 'Proje Yönetimi Gr2 A310 Dr. Şenim ÖZGÜRLER', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4480', 'İşletmelerde Verimlilik Gr1 A210 Öğr. Gör. Dr. Ufuk BÖLÜKBAŞ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4651', 'Quality Management Gr1 B201 Dr. Öğr. Üyesi Özge Nalan BİLİŞİ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4661', 'Industrial Engineering Design Project All Groups', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4810', 'Inventory Models Gr1 A105 Dr. Öğr. Üyesi Esra İLBAHAR', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4830', 'Yalın Üretim Gr2 B302 Öğr. Gör. Dr. Ufuk BÖLÜKBAŞ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4971', 'Facilities Planning and Control Gr1 B405 Doç. Dr. Doğan ÖZGE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4990', 'İstatistiksel Kalite Kontrol Gr1 B102 Prof. Dr. Coşkun ÖZKAN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'END4995', 'Agent Based Modeling and Simulation Gr1 A313 Doç. Dr. Mert E', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT1320', 'Linear Algebra Gr34 B301', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MAT2411', 'Differential Equations Gr55 ONLINE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('END', 'MFK4991', 'Multidisciplinary Design Project Mechatronic Eng.+Mechanical', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH3446', 'Mikro Fly ERP ile Dijital Üretim Yönetimi Gr1 A205', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('END', 'MTH4800', 'Innovation Campus Artificial Intelligence (Samsung) Gr1 ONLI', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('GDA', 'ATA1031', 'Atatürk İlke ve İnk', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'FIZ1001', 'Fizik 1 (Gr.28) KMB-214 MAT2411 Diferansiyel Denklemler (Gr.', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı, Çarşamba'), 
    ('GDA', 'GDM9000', 'Bitirme Çal', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM1170', 'Genel Kimya (Gr.7)  KMB-328 GDM 2301  G', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma, Salı'), 
    ('GDA', 'MAT1071', 'Matematik 1 (Gr.25) Online GDM3251 Is', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi, Salı'), 
    ('GDA', 'MDB1031', 'İleri İngilizce 1 (Gr.34) KME-305', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'TDB1031', 'Türkçe 1 Online MAT2411 Diferansiyel Denklemler (Gr.18) Onli', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM2091', 'Kütle ve Enerji Denklikleri                                 ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM2112', 'İş Sağl', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM2181', 'Genel Mikrobiyoloji                               Doç. Dr. B', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Salı'), 
    ('GDA', 'KIM2301', 'Analitik Kimya (Gr.1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Perşembe'), 
    ('GDA', 'GDM3211', 'Enstrümental Analizler (Lab)                                ', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Cuma'), 
    ('GDA', 'GDM3261', 'Reaksiyon Kinetiği                                          ', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM3271', 'Girişimcilik ve Proje Yönetimi                     Dr. Öğr. ', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('GDA', 'GDM4303', 'Su Ürünleri İşleme Teknolojisi                              ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4305', 'Süt ve Ürünleri Teknolojisi                            Prof.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Çarşamba'), 
    ('GDA', 'GDM4307', 'Et ve Ürünleri Teknolojisi  (EN)                            ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'ATA1031', 'Atatürk İlkeleri ve İnklap Tarihi 1 Gr.14', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'ATA1031', 'Atatürk İlkeleri ve İnklap Tarihi 1 Gr.14', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'FIZ1001', 'Physics 1 Gr.55 (KMB 316) Gr.56 (KMB 322)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KIM1501', 'General Chem. 1 Gr.1 (KMB 316) Gr.2 (KMB 314)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KIM1501', 'Genel Kimya 1 Gr.3 (KMB 210) Gr.4 (KMB 218)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM1041', 'Int. to Chem. Eng. Gr.2 D.Dinçer (KMB 210) Gr.3 İ.Küçük (KME', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM1041', 'Kimya Müh.Giriş Gr.1 İ. Doymaz (KMB 210)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT1071', 'Mathematics 1 Gr.53', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT1071', 'Matematik 1 Gr.22', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MDB1031', 'Adv. English 1 Gr.37 (KME 304)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MDB1031', 'İleri İng. 1 Gr.36 (KMB 305)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'TDB1031', 'Türkçe 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'TDB1031', 'Türkçe 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'FIZ1001', 'Physics 1 Gr.55 (KMB 316) Gr.56 (KMB 322)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB3631', 'Artificial Intelligence for Chemical Engineers Gr.1 (M. A. İ', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2601', 'Occ. Health & Safety-1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2611', 'Chem. Eng.Calc.', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2621', 'Phy. Chem. For Eng. Gr.3 T. Gösterişli (KMB 322) Gr.4 F. Dum', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2631', 'Probability and Statistics for Engineers', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3561', 'UMS  Technical Communication (E. Akyol)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT2411', 'Differential Equations Gr.52', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB2631', 'Mühendisler için Olasılık ve', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2601', 'İş Sağlığı ve Güv. 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2611', 'Kimya Müh. Hesap.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2621', 'Müh. için Fiz. Kimya Gr.1 S. Deniz (KMB 316) Gr.2 Y. Kalpakl', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3501', 'Ent. & Project Man.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3511', 'Numerical Analysis', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3521', 'Heat Transfer in Chem. Eng.', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3531', 'Chemical Eng. Thermo. 2', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3541', 'Mass Transfer', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3551', 'Env. Technology Gr.2 J. Gülen', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3561', 'UMS  Teknik İletişim (N. Tuğrul)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3591', 'Analysis Methods in Chemical Industry Gr.2 E. Derun', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4671', 'Chemical Engineering Economics Gr. 2 T. U. Gösterişli', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'MAT2411', 'Dif. Denk. Gr.15', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMB3631', 'Artificial Intelligence for', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM2631', 'Probability and Statistics for', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3501', 'Giriş. ve Proje Yön.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3511', 'Sayısal Analiz Gr.1 N. Acaralı (KMB 322)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3521', 'Kimya Müh. Isı Aktarımı', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3531', 'Kimya Müh. Termodinamiği 2', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3541', 'Kütle Aktarımı Gr.1 İ. Özgündüz (KMB 218)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3551', 'Env. Technology Gr.2 J. Gülen', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3571', 'Yakıtlar ve Yakıt Tek. (O. İsmail) KMM3581 Enerji Tasarrufu ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3591', 'Analysis Methods in Chemical', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM3611', 'Kimya End. Kalite Kontrol (Y. Kalpaklı)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4000', 'Graduation Thesis', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4000', 'Bitirme Çalışması', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4611', 'Pro. Des. in Chemical Eng. I', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4611', 'Kimya Müh. Proses Tasarımı 1 Gr.1 Y. Salt (KMB 210), Gr.2 İ.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4621', 'Chemical Reactor Design', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4621', 'Kimyasal Reaktör Tasarımı Gr.1 B. Özbek (KMB 314) Gr.2 E. Yı', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4631', 'Process Dynamics and Control Gr.2 E. Yılmaz (KMB 314) Gr.3 E', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4631', 'Proses Dinamiği ve Kontrolü Gr.1 M. Akgün (KMB 316)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4641', 'W. Recyc. Gr.2 J. Gülen KMM4691 Bioseperation (M. Yılmaz)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4641', 'Atık Geri Dön. Gr.1 N. Tuğrul', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4651', 'Bio. E. Fund. (B. Özbek)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4651', 'Bio. E. Fund. (B. Özbek)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4661', 'Gıda Tek. Temel İş. (İ. Doymaz)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4671', 'Chemical Engineering Economics Gr 2 T. U. Gösterişli', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4681', 'Pol. Üretimi ve', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4711', 'Elektro.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4721', 'Opt. in Chem. Eng. Gr.2 H. Sadıkoğlu', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4721', 'Opt. in Chem. Eng. Gr.2 H. Sadıkoğlu', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4731', 'Memb. ve', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4741', 'Yeni ve', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4751', 'Calc. in Multi-Component Sep. Systems', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('KIM', 'KMM4751', 'Calc. in Multi-Component Sep.', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'FIZ1001', '.01 DZ-132', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1051', '.05 Öğr.Gör.Dr. SEYHAN ÖZEN A410 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1061', '.01 Öğr.Gör. Umut KINIT A313 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1062', '.01 Arş.Gör.Dr. Özlem EMANET A209 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2071', '.02 Doç.Dr. MİNE USLU UYSAL A205 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2112', '.01 Doç.Dr. ABDÜLKERİM OKBAZ A308 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3182', '.01 Doç.Dr. Cihan DEMİR A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3201', '.01 Dr.Öğretim Üyesi SERKAN ERDEM A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3301', '.01 Prof.Dr. Ali PINARBAŞI A416 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3471', '.01 Doç.Dr. LEVENT YÜKSEK B401 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4391', '.01 Doç.Dr. Meral BAYRAKTAR A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4571', '.01 Arş.Gör.Dr. ÖZGÜN BALCI A406 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4651', '.01 Prof.Dr. Ahmet Selim DALKILIÇ A211 (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT1071', '.31 Online', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MDB1031', '.14 E1 Toplantı Salonu* (Yıldız)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'ATA1031', '.04 Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK1071', '.01 Prof.Dr. Özden AĞRA Yıldız - Oditoryum (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK1072', '.01 Dr.Öğretim Üyesi ALPARSLAN SOLAK B102 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2011', '.01 Prof.Dr. Anıl AKDOĞAN B103 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2061', '.02 Doç.Dr. ASLI GÜNAY BULUTSUZ A310 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2081', '.02 Doç.Dr. MİNE USLU UYSAL A107 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2091', '.01 Prof.Dr. Derya Burcu ÖZKAN A313 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2101', '.01 Prof.Dr. Hadi GENCELİ A319 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2142', '.01 Doç.Dr. NURULLAH KAYACI A319 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2212', '.01 Arş.Gör.Dr. KEREM ASMAZ A308 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK2482', '.01 Öğr.Gör.Dr. İSRAFİL SÖYLER Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK3071', '.01 Arş.Gör.Dr. İLKAY KURT B205 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3091', '.04 Prof.Dr. Mehmet BOZCA A105 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3151', '.01 Prof.Dr. Hasan Hüseyin ERDEM E202 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3191', '.01 Doç.Dr. Nuri Alpay KÜREKCİ E202 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3271', '.02 Prof.Dr. Sebiha YILDIZ A210 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3281', '.01 Doç.Dr. LEVENT YÜKSEK B403 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3291', '.02 Doç.Dr. YASİN KARAGÖZ A113 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3391', '.01 Doç.Dr. ORHAN ÇAKIR A105 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3401', '.01 Doç.Dr. İlyas İSTİF B205 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3431', '.01 Doç.Dr. ALİ SERDAR VANLI A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3441', '.01 Doç.Dr. Tolga MERT A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3461', '.01 Doç.Dr. BORA ŞENER A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3561', '.01 Prof.Dr. Tarkan SANDALCI B103 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3652', '.01 Arş.Gör. NURHAN ÜREGEN GÜLER B103 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3671', '.01 Prof.Dr. Emrullah Hakan KALELİ A114 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3681', '.01 Prof.Dr. Ahmet Selim DALKILIÇ A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK3691', '.01 Prof.Dr. Deniz ULUSARSLAN A209 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4072', '.01 Dr.Öğretim Üyesi OKAN BAKBAK A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4092', '.01 Dr. DAĞHAN DOĞAN Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4261', '.01 Prof.Dr. Deniz ULUSARSLAN A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4291', '.01 Öğr.Gör. Fehmi GÜÇLÜ A415 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4401', '.01 Doç.Dr. Nadir JAVANİ B403 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4422', '.01 Dr.Öğretim Üyesi FATİH SORGULU A205 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4451', '.04 Doç.Dr. Meral BAYRAKTAR A209 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4471', '.01 Arş.Gör.Dr. Barbaros BATUR Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4472', '.01 Arş.Gör.Dr. Barbaros BATUR Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4482', '.01 Arş.Gör.Dr. İLKAY KURT Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'MAK4491', '.01 Doç.Dr. Berna BOLAT A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4541', '.01 Prof.Dr. MİHRİGÜL EKŞİ ALTAN A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4591', '.01 Prof.Dr. Ahmet Selim DALKILIÇ A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4595', '.01 Dr.Öğretim Üyesi FATİH GÜVEN A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4601', '.01 Arş.Gör.Dr. Özlem EMANET A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4801', '.01 Doç.Dr. Nuri Alpay KÜREKCİ A406 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4891', '.01 Arş.Gör.Dr. Mustafa Kemal SEVİNDİR A114 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4921', '.01 Prof.Dr. Emrullah Hakan KALELİ A114 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4931', '.01 Prof.Dr. Muammer ÖZKAN A318 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4933', '.01 Doç.Dr. Alp Tekin ERGENÇ A114 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAK4941', '.01 Doç.Dr. Murat KIYAK A211 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT1320', '.22 B303 (Yıldız)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAK', 'MAT2411', '.24 Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAK', 'TDB1031', '.34 Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'FIZ1001', 'Fizik 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MDB1031', 'İleri İngilizce 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1501', 'Analiz 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1511', 'Programlama Dilleri 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM1551', 'İş Sağlığı ve Güvenliği 1 (ONLINE)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM1561', 'Matematik Mühendisliğine Giriş (ONLINE)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2501', 'İleri Analiz 1', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2511', 'Algoritmalar ve Veri Yapıları (ONLINE)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM2521', 'Nümerik Analiz I', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM2531', 'Diferansiyel Denklemler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3611', 'Matematik Tarihi Gr.1 KMB-320', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'TDB1031', 'TÜRKÇE 1 (ONLINE)', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'ATA1031', 'ATA 1 (ONLINE)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3511', 'Bilgisayar Tasarımı / MTM3671 Çizge Kur. Ve Alg. MTM3591 Bul', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3551', 'İntegral Dön./ MTM3661 Mat. Lojik / MTM3721 Soyut Mat. MTM35', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3641', 'Bilgisayar Des. Mat. Hesap. / MTM3681 Fourier Analizi MTM360', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3651', 'İstatistik', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM3691', 'Lineer Programlama Teorisi (ONLINE)', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM3701', 'Mekanik 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM4501', 'Yöneylem Araştırması (ONLINE)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4641', 'Veri Madenciliğine Giriş (2G) MTM4681 Mobil Programlama', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MAT', 'MTM4661', 'Nesneye Yön. İleri Prog. / MTM4591 Elastisite Teo. MTM4581 O', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4691', 'Bilg. Tab. Öğr. Sistemler / MTM4541 Dinamik MTM4571 Müh. Pro', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MAT', 'MTM4711', 'Matematiksel Modelleme (ONLINE)', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'ATA1031', 'Atatürk İlkeleri ve Ink. Tarihi ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'ATA1031', 'Atatürk İlkeleri ve Ink. Tarihi ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'FIZ1001', 'PHYSICS 1 GR.39 ON-LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'FIZ1001', 'PHYSICS 1 GR.39 ON-LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT1071', 'MATHEMATICS 1 Gr.59 ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT1071', 'MATHEMATICS 1 Gr.59 ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MDB1031', 'Advanced English 1 GR.51 KMB317', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MDB1031', 'Advanced English 1 GR.51 KMB317', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/C', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1001', 'Impact of Engineering Practices on Society and Environment/C', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1321', 'Academic Research Techniques F.AKYOL KMB313', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE1911', 'Statistics B.C.FİLİZ (Online)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'MSE1911', 'Statistics B.C.FİLİZ (Online)', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'TDB1031', 'TURKISH LANGUAGE 1 ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'TDB1031', 'TURKISH LANGUAGE 1 ON LINE', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'KMM3501', 'ENTREPRENEURSHIP AND PROJECT MANAGEMENT GR.4 ON-LINE A.AYDIN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'KMM3501', 'ENTREPRENEURSHIP AND PROJECT MANAGEMENT GR.4 ON-LINE A.AYDIN', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT2411', 'DIFFERENTIAL EQUATIONS Gr.57 ON-LINE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MAT2411', 'DIFFERENTIAL EQUATIONS Gr.57 ON-LINE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2091', 'Mass and Energy Balance S.AVCIOĞLU KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2091', 'Mass and Energy Balance S.AVCIOĞLU KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2101', 'Applied Engineering Mathematics Gr.1 F.AKYOL KMB329-B', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2101', 'Applied Engineering Mathematics Gr.1 F.AKYOL KMB329-B', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2711', 'Materials Science G.1 F.KAYA KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2711', 'Materials Science G.1 F.KAYA KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2911', 'Statics and Strength of Materials M.YILMAZ KMB312', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2911', 'Statics and Strength of Materials M.YILMAZ KMB312', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2921', 'Thermodynamics of Materials A.E.ERSUNDU KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2921', 'Thermodynamics of Materials A.E.ERSUNDU KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE2941', 'OCCUPATIONAL HEALTH AND SAFETY 1 GR.1 M.YILMAZ ONLINE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'MSE2941', 'OCCUPATIONAL HEALTH AND SAFETY 1 GR.1 M.YILMAZ ONLINE', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MET', 'MSE3072', '(MES4)  Physical Properties of Materials F.AKYOL KMB312', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3072', '(MES4)  Physical Properties of Materials F.AKYOL KMB312', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3271', '(MES1)  Metrology and Calibration N.DUYGULU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3271', '(MES1)  Metrology and Calibration N.DUYGULU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3381', 'Transport Phenomena M.D.ÇALIŞIR KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3381', 'Transport Phenomena M.D.ÇALIŞIR KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3401', '(MES3)  Hydrometallurgy M.GENÇTEN KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3401', '(MES3)  Hydrometallurgy M.GENÇTEN KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3411', '(MES3)  Glass Technology A.E.ERSUNDU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3411', '(MES3)  Glass Technology A.E.ERSUNDU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3421', '(MES3)  Non-Ferrous Metals Metallurgy B.BİROL KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3421', '(MES3)  Non-Ferrous Metals Metallurgy B.BİROL KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3501', '(MES1)  Welding Technology A.KISASÖZ KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3501', '(MES1)  Welding Technology A.KISASÖZ KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3521', '(MES1)  MANUFACTURING METHODS OF CERAMICS B.ÇİÇEK KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3521', '(MES1)  MANUFACTURING METHODS OF CERAMICS B.ÇİÇEK KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3531', '(MES1)  Machine Elements for Engineers A.S.NAZLIGÜL KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3531', '(MES1)  Machine Elements for Engineers A.S.NAZLIGÜL KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3571', '(MES1)  Electrometallurgy J.H.ÖZDEMİR KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3571', '(MES1)  Electrometallurgy J.H.ÖZDEMİR KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3581', '(MES1)  Advanced Ceramics G.Ş.FRANCİ KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3581', '(MES1)  Advanced Ceramics G.Ş.FRANCİ KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3591', '(MES1)  Medical Device Regulations and Processes A.AYDINOĞLU', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3591', '(MES1)  Medical Device Regulations and Processes A.AYDINOĞLU', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3901', '(MES4)  Mechanical Properties of Materials A.ALTINBAY KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3901', '(MES4)  Mechanical Properties of Materials A.ALTINBAY KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3911', 'Principles of Solidification R.GECÜ KMB303', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3911', 'Principles of Solidification R.GECÜ KMB303', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3941', 'Iron and Steelmaking B.BİROL KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE3941', 'Iron and Steelmaking B.BİROL KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4071', '(MES3)  Biomedical Materials N.K.SUMAMA KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4071', '(MES3)  Biomedical Materials N.K.SUMAMA KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4081', '(MES3)  Nano Materials N.K.SUMAMA KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4081', '(MES3)  Nano Materials N.K.SUMAMA KMB217', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4121', 'Material Production Laboratory 1 S.AVCIOĞLU', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4121', 'Material Production Laboratory 1 S.AVCIOĞLU', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4131', '(ÜMS)  Material World (Univ.Prof.Electiv) B.Ö.KISASÖZ (Metal', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4131', '(ÜMS)  Material World (Univ.Prof.Electiv) B.Ö.KISASÖZ (Metal', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4591', '(MES2)  Interdisciplinary Design Application in Materials Te', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4591', '(MES2)  Interdisciplinary Design Application in Materials Te', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4621', 'Metallurgy Kinetics M.Ç.ERSUNDU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4621', 'Metallurgy Kinetics M.Ç.ERSUNDU KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4631', 'Corrosion and Prevention O.K. ÖZDEMİR KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4631', 'Corrosion and Prevention O.K. ÖZDEMİR KMB313', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4831', '(MES2)  DESIGN APPLICATIONS IN METALLURGICAL PRODUCTION', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4831', '(MES2)  DESIGN APPLICATIONS IN METALLURGICAL PRODUCTION', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4841', '(MES2)  DESIGN APPLICATIONS IN MATERIAL TECHNOLOGIES', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4841', '(MES2)  DESIGN APPLICATIONS IN MATERIAL TECHNOLOGIES', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4851', '(MES2)  DESIGN APPLICATIONS IN CERAMIC TECHNOLOGIES', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4851', '(MES2)  DESIGN APPLICATIONS IN CERAMIC TECHNOLOGIES', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4861', '(MES1)  MATERIALS FOR DEFENCE INDUSTRY B.ÇİÇEK KMB303', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4861', '(MES1)  MATERIALS FOR DEFENCE INDUSTRY B.ÇİÇEK KMB303', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4881', '(MES1)  Polymer Processing H.BERBER KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4881', '(MES1)  Polymer Processing B.Ö.KISASÖZ KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4891', '(MES1)  Automotive Materials S.ACAR KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4891', '(MES1)  Automotive Materials S.ACAR KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4911', '(MES1)  Functional Materials S.DELİKANLI KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4911', '(MES1)  Functional Materials S.DELİKANLI KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4931', '(MES1)  Ferroalloy Production Methods H.YILMAZER KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4931', '(MES1)  Ferroalloy Production Methods H.YILMAZER KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4941', '(MES1)  Advanced Structural Steels A.KISASÖZ KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4941', '(MES1)  Advanced Structural Steels A.KISASÖZ KMB317', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4951', '(MES1)  Aerospace and Aviation Materials A.SAĞIN KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MET', 'MSE4951', '(MES1)  Aerospace and Aviation Materials A.SAĞIN KME307', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT1071', '| Gr33 Matematik 1 Online', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MAT1320', '| Gr24 Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MDB1031', '| Gr25 İleri İngilizce 1 E1 Salonu* ────────────────  | Gr26', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1801', '| Gr01 İş Sağlığı ve Güvenliği Öğr. Gör. Dr. Gökçe Sönmez On', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT1821', '| Gr01 Mekatronik Müh. Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'FIZ1001', '| Gr43 Fizik 1 Doç. Dr. Serpil Yalçın Kuzu DZ-138', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1111', '| Gr02', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT1831', '| Gr02 Lab 1 - Atölye ve İmalat', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MAT2411', '| Gr27', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2141', '| Gr01 Analog Elektronik Dr. Öğr. Üyesi Onurcan Şahin Yıldız', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2161', '| Gr01', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2412', '| Gr01 Mühendisler için İstatistik Dr. Öğr. Üyesi Salih Obut', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT2831', '| Gr01 Lab 2 - Elektrik ve Elektronik', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'TDB1031', '| Gr35 / Gr36 Türk Dili 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'ATA1031', '| Gr06 Atatürk İlkeleri ve İnkılap Tarihi 1', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MFK4991', '| Gr01 Çok Disiplinli Tasarım Projesi Online', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT2151', '| Gr02 Nesneye Yönelik Programlama Dr. Öğr. Üyesi Ertuğrul', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3411', '| Gr01 Akışkanlar Mekaniği Prof. Dr. Ahmet Koyun B103', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3413', '| Gr01 Isı Geçişi Dr. Öğr. Üyesi Parisa Heidarnejad B401 ───', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3421', '| Gr01 İşaretler ve Sistemler Prof. Dr. Aydın Yeşildirek B40', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3801', '| Gr02', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3811', '| Gr01 Mikroişlemciler ve Programlanması Doç. Dr. Hüseyin Ay', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3821', '| Gr01 Makine Elemanları', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT3841', '| Gr02 Sayısal Yöntemler Prof. Dr. Cüneyt Yılmaz B102', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4111', 'MKT4000 Mekatornik Sistem Tasarımı / Bitirme Çalışması Ekip ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4403', '| Gr01 Mekatronik Sistem Entegrasyonu Dr. Esra Çelik A209', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4441', '| Gr01 İmalat Yöntemleri Prof. Dr. Haydar Livatyalı', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4443', 'A114 ───────────  | Gr01 Proses Tekniği Dr. Parisa Heidarnej', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4451', '| Gr01 Elektriksel Tahrik Sistemleri Prof. Dr. Cenk Ulu A403', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4453', '| Gr01 Yeni Nesil Elektrik Motorları Doç. Dr. Muhammet Garip', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4461', '| Gr01 Proje Yönetimi Doç. Dr. Hüseyin Üvet B402 ───────────', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4802', '| Gr01 Lab 4 - Motorlar ve Sürücüler', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4820', '| Gr01 Sayısal İşaret İşleme Dr. Yakup Özsezer A308', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4830', '| Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4831', '| Gr01 Robot Mühendisliği Prof. Dr. Vasfi Emre Ömürlü A416', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4837', '| Gr01 Optomekatroniğe Giriş Dr. Öğr. Üyesi Onurcan Şahin', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT4848', '| Gr01 Pekiştirmeli Öğrenme Dr. Öğr. Üyesi Mehmet İşcan A105', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5001', '| Gr01 Yüksek Lisans Seminer Dr. Öğr. Üyesi Kemal Mert Doğan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5112', '| Gr01 Linear System Theory Prof. Dr. Cüneyt Yılmaz A113', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5115', '| Gr01 Systems Engineering in Mechatronics Doç. Dr. Hüseyin ', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5120', '| Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5121', '| Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5125', '| Gr01', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT5127', '| Gr01 Ürün Tasarımı ve Girişimcilik Prof. Dr. Ahmet Koyun', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6001', '| Gr01 Yüksek Lisans Seminer Dr. Öğr. Üyesi Kemal Mert Doğan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6107', '| Gr01 Mekatronikte Yapay Zeka Prof. Dr. Erhan Akdoğan A410', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6108', '| Gr01 Mekatronikte Özel Konular Dr. Öğr. Üyesi Mehmet İşcan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 1, 'Pazartesi'), 
    ('MKT', 'MKT6116', '| Gr01 Mühendislik Matematiği 2 Dr. Öğr. Üyesi Parisa Heidar', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6119', '| Gr01 Newtonyen Olmayan Akışkanlar Doç. Dr. Hatice Mercan', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MKT6125', '| Gr01 Fuzzy Modeling and Control Prof. Dr. Cenk Ulu A416', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('MKT', 'MTH4701', '| Gr01 Elektrikli Araçlarda Güç Dönüşümü Dr. Fatih Eroğlu', 4, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'FIZ1001', '.46 / .47 Fizik 1 *', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1071', '.56', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MAT1320', '.33 Lineer Cebir', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'MDB1031', '.47', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'RAMI2026', 'ELEKTRİK ELEKTRONİK FAKÜLTESİ YAPAY ZEKA VE VERİ MÜHENDİSLİĞ', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1011', 'Yapay Zekanın Temelleri', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1021', 'Programlamaya Giriş', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1041', 'İş Sağlığı ve Güvenliği 1', 1, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM1042', 'İş Sağlığı ve Güvenliği 2', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2021', 'Yazılım Mühendisliğinin İlkeleri', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2031', 'Veri Yapıları ve Algoritmalar', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2042', 'Lojik ve Mikroişlemciler', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2061', 'İstatistik ve Olasılık', 2, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'ATA1031', '.05 Atatürk İlkeleri ve İnkılap Tarihi 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'TDB1031', '.33 Türkçe 1', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM2002', 'Genel Staj (STAJ) - Öğr. Gör. Dr. Fettah Kıran', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3011', 'Doğal Dil İşleme', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3012', 'Derin Öğrenmeye Giriş', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3021', 'Algoritma Analizi', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
    ('YZV', 'YZM3031', 'Bilgisayarla Görü', 3, 0, 3, 5, 'Bölüm Öğretim Üyeleri', 0, 'Pazartesi'), 
]

def seed_all():
    init_db()
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # Add days column if missing
    try:
        c.execute("ALTER TABLE courses ADD COLUMN days TEXT")
    except Exception:
        pass
    # Only seed if empty
    c.execute("SELECT COUNT(*) FROM courses")
    count = c.fetchone()[0]
    if count > 0:
        print(f"DB already has {count} courses, skipping seed.")
        conn.close()
        return
    c.executemany(
        "INSERT INTO courses (department_code, code, name, year, is_elective, credits, ects, instructor, is_online, days) VALUES (?,?,?,?,?,?,?,?,?,?)",
        ALL_COURSES
    )
    conn.commit()
    conn.close()
    print(f"Seeded {len(ALL_COURSES)} courses into DB.")

if __name__ == "__main__":
    seed_all()